apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: "redis"
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
        command: ["redis-server"]
        args: ["--save", "900", "1", "--save", "300", "10", "--dir", "/data"]
        livenessProbe:
          exec:
            command:
            - redis-cli
            - -h
            - localhost
            - ping
          initialDelaySeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - -h
            - localhost
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 5
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
