global:
  scrape_interval: 15s  
  evaluation_interval: 15s  

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - 10.0.2.26:9100  
  - job_name: 'loki'
    static_configs:
      - targets:
          - 10.0.2.115:3100

  - job_name: 'prometheus'
    static_configs:
      - targets:
          - localhost:9090
  - job_name: 'nginx'
    static_configs:
      - targets: 
          - 10.0.2.26:9113

rule_files:
  # Добавляем файлы алертов, если они есть
  # - "alert_rules.yml"
