[webservers]
node1 ansible_host=192.168.56.3 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/node1/virtualbox/private_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[dbservers]
node2 ansible_host=192.168.56.4 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/node2/virtualbox/private_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'
