Vagrant.configure("2") do |config|
  # Настройка первой виртуальной машины
  config.vm.define "node1" do |node1|
    node1.vm.box = "generic/ubuntu2204"
    node1.vm.hostname = "node1"
    node1.vm.network "private_network", type: "dhcp"
    node1.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = 1024
    end
  end

  # Настройка второй виртуальной машины
  config.vm.define "node2" do |node2|
    node2.vm.box = "generic/ubuntu2204"
    node2.vm.hostname = "node2"
    node2.vm.network "private_network", type: "dhcp"
    node2.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = 1024
    end
  end

  # Обеспечение доступности Ansible
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3 python3-apt
  SHELL
end
