version: '3.8'

services:
  nginx:
    image: "${NGINX_IMAGE}"
#    container_name: "${NGINX_CONTAINER_NAME}"
  #  ports:
 #     - "${NGINX_PORT}:80"
    volumes:
      - ./web-data:/usr/share/nginx/html
    networks:
      - appnet

  postgres:
    image: "${POSTGRES_IMAGE}"
    container_name: "${POSTGRES_CONTAINER_NAME}"
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - appnet

  redis:
    image: "${REDIS_IMAGE}"
    container_name: "${REDIS_CONTAINER_NAME}"
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - appnet

volumes:
  db-data:
  web-data:

networks:
  appnet:
