version: '3.8'
services:
  mongo:
    image: "${MONGO_IMAGE}"
    container_name: "${MONGO_CONTAINER_NAME}"
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"
    command: --bind_ip_all
    volumes:
      - ./mongo-data:/data/db
volumes:
  mongo-data:
